/**
 * PAGE-COPY.JS
 * Genuinely unique, hand-written intro copy for every generated
 * landing page. Kept separate from generate-seo-pages.js so this
 * can be edited/expanded without touching generator logic. Each
 * entry is a real paragraph of original context - not a template
 * with the category name swapped in - to avoid the "thin/templated
 * content" problem search engines penalize.
 */

const SECTOR_COPY = {
  'ai': "Artificial intelligence has become the single most contested category in venture capital, spanning foundation model developers, AI infrastructure providers, and vertical AI applications rebuilding entire industries from the ground up. The firms below range from mega-funds writing nine-figure checks into frontier labs to specialist seed investors betting on AI-native startups before the category had a name.",
  'fintech': "Fintech investing spans neobanks, payments infrastructure, lending platforms, and the specialist firms - often founded by former bankers and fintech operators themselves - who understood the regulatory and unit-economics complexity of financial services long before generalist VCs did. Several of the firms below trace their own founders back to companies like Capital One, giving them a genuinely different lens on the category.",
  'crypto': "Crypto and Web3 investing has moved through multiple boom-and-bust cycles since Bitcoin's earliest days, and the firms below range from dedicated crypto-native funds to generalist firms that made early, high-conviction bets on category leaders before the space had institutional legitimacy.",
  'healthcare': "Healthcare venture capital covers a genuinely wide range of risk profiles, from Flagship Pioneering's internal company-creation model that built Moderna from scratch, to growth-stage specialists like HealthQuest Capital that only back companies already generating real commercial revenue. The firms below span biotech, medical devices, diagnostics, and digital health.",
  'climate': "Climate technology investing requires patience and deep technical fluency that most generalist funds don't have - many of the firms below were founded by former engineers or scientists specifically because evaluating hard climate hardware (batteries, fusion, carbon removal, grid technology) demands real domain expertise, not just financial modeling.",
  'cybersecurity': "Cybersecurity has become one of venture capital's most specialized categories, with several firms below - Forgepoint Capital, YL Ventures, Cyberstarts - investing exclusively in the space and building deal networks around practicing CISOs rather than generalist technology scouts. The category also produced one of the largest venture-backed exits in history.",
  'enterprise-software': "Enterprise software remains venture capital's most durable category, spanning SaaS, vertical software, and infrastructure tooling that businesses depend on daily. The firms below range from mega-funds with decades of enterprise pattern recognition to focused seed specialists betting on the next generation of B2B category leaders.",
  'consumer': "Consumer investing swings between overheated hype cycles and genuine long-term conviction, and the firms below include some of the category's most disciplined specialists - including funds built by former retail equity analysts who apply the same rigor to unit economics that public-market investors use.",
  'deep-tech': "Deep tech investing means underwriting genuine scientific and engineering risk - semiconductors, robotics, aerospace, and frontier physics - rather than software business-model risk. The firms below often maintain in-house technical benches of PhDs and former operators specifically to evaluate bets most VCs can't meaningfully assess.",
  'defense-tech': "Defense technology has moved from a category most venture firms avoided entirely to one of the fastest-growing areas of institutional interest, driven by geopolitical shifts and a new generation of dual-use startups building for both commercial and government customers.",
  'marketplaces': "Marketplace businesses live or die on network effects, and the firms below include specialists who've spent over a decade researching and codifying exactly how those network effects form, scale, and defend themselves against competition.",
  'developer-tools': "Developer tools and cloud infrastructure investing rewards firms with genuine technical depth, since evaluating a database, an API platform, or a dev-ops tool requires understanding how engineering teams actually work - not just reading a pitch deck.",
  'mobility': "Mobility and logistics technology spans ride-sharing, autonomous vehicles, supply chain software, and the physical infrastructure connecting them, backed by firms ranging from Silicon Valley generalists to corporate strategic investors like Toyota Ventures and BMW i Ventures with direct industry stakes.",
  'edtech': "Education technology investing has produced fewer venture-scale outcomes than most categories, making the firms below - who've stayed committed through multiple hype-and-correction cycles - a genuinely differentiated group within the broader venture landscape.",
  'industrial-tech': "Industrial and manufacturing technology investing means underwriting physical, capital-intensive businesses that most software-focused VCs pass on, rewarding firms willing to hold hardware-heavy positions through much longer development timelines than typical SaaS investments.",
};

const LOCATION_COPY = {
  'silicon-valley': "Silicon Valley remains the single largest concentration of venture capital firms tracked on this page, spanning the full spectrum from Sand Hill Road mega-funds managing tens of billions to solo-GP seed specialists operating out of Palo Alto and Menlo Park. The region's density of firms, founders, and prior exits continues to compound in ways few other ecosystems have replicated.",
  'new-york': "New York's venture ecosystem has matured from a fintech-and-media-adjacent afterthought into a genuine rival to Silicon Valley, anchored by firms spanning early-stage specialists to some of the largest growth-equity platforms in the industry, many purpose-built around New York's particular strength in financial services and enterprise software.",
  'boston': "Boston and Cambridge host one of the most concentrated biotech and life sciences venture ecosystems in the world, anchored by proximity to MIT, Harvard, and a dense cluster of teaching hospitals - several of the firms below were built specifically to commercialize research coming directly out of that academic corridor.",
  'los-angeles': "Los Angeles' venture ecosystem has grown well beyond its media and entertainment roots into a genuine multi-sector hub, with firms below spanning consumer, enterprise, and deep tech investing across the broader LA basin.",
  'europe': "European venture capital has matured into a genuinely global-competitive ecosystem over the past two decades, producing firms that built some of the continent's first true technology giants - Skype, Spotify, Wise, UiPath - while maintaining a distinctly different pace and structure than their Silicon Valley counterparts.",
  'israel': "Israel's venture ecosystem punches dramatically above its size, and the firms below reflect a distinctly Israeli pattern: many founders spent years in elite military intelligence units before building or investing in cybersecurity and deep tech companies that went on to some of the largest exits in venture history.",
  'asia-pacific': "Asia-Pacific venture capital spans dramatically different markets - from India's rapidly maturing startup ecosystem to Japan's decades-old independent VC institutions to Southeast Asia's mobile-first consumer internet boom - reflected in the genuinely varied set of firms below.",
  'latin-america': "Latin American venture capital was largely built from scratch by a small number of firms over the past two decades, several founded by operators who'd already built and taken public the region's first generation of technology category leaders before ever writing outside investor checks.",
};

const STAGE_COPY = {
  'pre-seed': "Pre-seed investing means backing a company before it has meaningful revenue, sometimes before it has a finished product - the firms below specialize in evaluating founder conviction and market timing with the least amount of concrete evidence to go on.",
  'seed': "Seed-stage investing remains venture capital's highest-volume, highest-risk category, and the firms below range from generalist mega-funds running dedicated seed programs to solo-GP specialists who've built entire careers around this single stage.",
  'series-a': "Series A investing sits at the inflection point where a company needs to show real evidence of product-market fit, and the firms below specialize in evaluating that transition from promising early traction to a genuinely scalable business.",
  'series-b': "Series B and growth-stage investing rewards firms with real operational pattern-recognition - helping companies professionalize go-to-market motions, scale organizations, and prepare for the increased scrutiny of later funding rounds and eventual public markets.",
  'growth': "Growth-stage investing means writing larger checks into companies with proven business models, often blending public-market and private-market investing disciplines - several of the firms below, like TCV and Dragoneer, pioneered exactly that crossover approach.",
  'late-stage': "Late-stage investing sits closest to the public markets, backing companies in the final stretch before IPO or acquisition, where firms need genuine expertise in capital markets timing alongside traditional venture judgment.",
};

module.exports = { SECTOR_COPY, LOCATION_COPY, STAGE_COPY };
